---
title: "Read Me: Script Overview"
date:  '`r format(Sys.time(), "%d %B, %Y")`'
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```



-------------------------------------------------------------------------------
# README OVERVIEW
-------------------------------------------------------------------------------
Author  : Logan Stundal
Date    : February 25, 2021
Purpose :
This document explains the order-of-operations in which to execute scripts that
replicate all analysis in the paper / appendix as well as produce all figures
and tables.

Additionally, data imports and data exports are noted for each script. All
imported and exported data files are stored in the Data/ directory.
-------------------------------------------------------------------------------



-------------------------------------------------------------------------------
# ISSUES
-------------------------------------------------------------------------------
1. Problem with projection in sp data - check 1.0 Spatial Admin 
  - CRS contains infomration on Australian datum???
-------------------------------------------------------------------------------



-------------------------------------------------------------------------------
# Main Paoer Scripts
-------------------------------------------------------------------------------


---------------------------------------
## 1.0: Spatial Admin
  - STATUS : DONE
  - Purpose: Prepares a simple features spatial object to hold all data for
             and analysis. As well, static geography variables such as
             distance from Bogota are estimated in this script.
  - Imports: Administrative-Units/col_admbnda_adm2_unodc_ocha.shp
  - Exports: colombia_admin.RData
---------------------------------------


---------------------------------------
## 2.0: Data Tidy
  - STATUS : DONE
  - Purpose: Organizes all variables used in models: event data, independent
             and control variables. Construct panel, grouped-years, and
             cross-section data structures
  - Imports: colombia_admin.RData
             event_data/gedicews_FARC_20190908.csv
             event_data/CINEP_HRV_Farc.dta
             covariates/Colombia_ForestCover_municipality_Panel.csv
             covariates/Colombia_Population_municipality_Panel.csv
             covariates/Colombia_tri_municipality_mean.csv
             covariates/Colombia_NightLights_municipality_Panel.csv
  - Exports: data_variables.RData
                  - colombia_pn [full panel]
                  - colombia_yg [years, grouped]
                  - colombia_cs [cross section]
---------------------------------------


---------------------------------------
## 3.0: EDA
  - STATUS : DONE
  - Purpose: Perform exploratory analysis on data including identifying
             municipalities with greatest FARC activity, estimating
             Cohen's Kappa, and confusion matricies as well as summary
             statistics.
  - Imports: data_variables.RData
  - Exports: Various figures to Plots/EDA/
---------------------------------------


---------------------------------------
## 3.1: EDA - Maps
  - STATUS : DONE
  - Purpose: Generates various plots of the distribution of the DVs as well as
             their spatial distributions.
  - Imports: data_variables.RData
  - Exports: Various figures to Plots/EDA/
---------------------------------------


---------------------------------------
## 3.2: EDA - Confusion Matrices
  - STATUS : DONE
  - Purpose: Produces extended confusion matrices as requested by reviewers.
  - Imports: data_variables.RData
  - Exports: 
---------------------------------------


---------------------------------------
## 4.0: Analysis - Continuous
  - STATUS : DONE
  - Purpose: Estimates SPDE models for all outcome variables [including appendix]
  - Imports: data_variables.RData
  - Exports:
---------------------------------------


---------------------------------------
## 5.0: Results - Tables - Continuous
  - STATUS : Rising
  - Purpose:
  - Imports:
  - Exports:
---------------------------------------


---------------------------------------
## 5.1: Results - CoefPlot - Continuous
  - STATUS : Rising
  - Purpose:
  - Imports:
  - Exports:
---------------------------------------


---------------------------------------
## 6.0: PostEst - ROC_PRC - Continuous
  - STATUS : Rising
  - Purpose:
  - Imports:
  - Exports:
---------------------------------------


---------------------------------------
## 6.1: PostEst - Range - Continuous
  - STATUS : Rising
  - Purpose:
  - Imports:
  - Exports:
---------------------------------------



-------------------------------------------------------------------------------



-------------------------------------------------------------------------------
# Appendix Scripts
-------------------------------------------------------------------------------

---------------------------------------
## 9.0: Analysis - Discrete
  - STATUS : Rising
  - Purpose: Estimate a series of discrete spatial lag and spatial error probit
             models.
  - Imports: data_variables.RData
             data_spatial.RData
  - Exports: models_discrete.RData
  - Notes  : Move the spatial lags to the appendix script later?
---------------------------------------


---------------------------------------
Failing: Spatial Tidy
  - STATUS : Failing
  - Reasons: Due to alignment and spatial weights - going to eventually incroporate
             this code into appendix discrete spatial probit code.
  - Purpose: Collects and organize spatial data used in models (spatial
             weights) or in figures (Colombia Admin 0 shapefile).
  - Imports: https://biogeo.ucdavis.edu/data/gadm3.6/Rsf/gadm36_COL_0_sf.rds,
                  - Colombia; Level-0 shapefile for mapping
             data_variables.RData
  - Exports: data_spatial.Rdata
---------------------------------------


---------------------------------------
x.x: xyz
  - STATUS : 
  - Purpose:
  - Imports:
  - Exports:
---------------------------------------
-------------------------------------------------------------------------------


-------------------------------------------------------------------------------

